# to get a secret key like this run:
# openssl rand -hex 32
SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
ALGORITHM: HS256
ACCESS_TOKEN_EXPIRE_MINUTES: 480

# PWD context settings
CRYPT_CONTEXT_SCHEME: bcrypt
PWD_CONTEXT_DEPRECATED: auto

# oauth2_scheme
TOKEN_URL: token

# Database settings
# for Alembic use alembic.ini in root
DATABASE_URL: postgresql+asyncpg://pgmain_dbuser:thOxk3whURJOaM2yMOchDAGc1QICQ88@localhost/mkd_works_serv_db
#Security scope settings
SELF_USER_SCOPE: me
ADMIN_SCOPE: admin
MANAGEMENT_MKD_WORKS_SCOPE: management_mkd_works

# Service settings
FILE_SERVER: localhost
FILE_SERVER_PORT: 8050
ACT_FILES_STORE_PATH: /mnt/d/Projects/hcs_media/acts
SMETA_FILES_STORE_PATH: /mnt/d/Projects/hcs_media/acts