"""Initial

Revision ID: ffd5df10ca6c
Revises: 
Create Date: 2022-10-31 11:54:20.273954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffd5df10ca6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_il',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('house', sa.String(), nullable=False),
    sa.Column('appartment', sa.String(), nullable=False),
    sa.Column('property_self', sa.Boolean(), nullable=True),
    sa.Column('il_number', sa.String(), nullable=False),
    sa.Column('il_date', sa.DateTime(), nullable=True),
    sa.Column('ur_in_work', sa.Boolean(), nullable=True),
    sa.Column('gov_tax', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('order_cancel', sa.Boolean(), nullable=True),
    sa.Column('bailiff_forward_date', sa.DateTime(), nullable=True),
    sa.Column('start_exec_pross_date', sa.DateTime(), nullable=True),
    sa.Column('sum_all_get', sa.DECIMAL(precision=24, scale=2), nullable=True),
    sa.Column('sum_not_yet_get', sa.DECIMAL(precision=24, scale=2), nullable=True),
    sa.Column('payments', sa.DECIMAL(precision=24, scale=2), nullable=True),
    sa.Column('debt_sum_il', sa.DECIMAL(precision=24, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_all_il_id'), 'all_il', ['id'], unique=False)
    op.create_table('passport_il',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('who_take', sa.String(), nullable=True),
    sa.Column('date_take', sa.DateTime(), nullable=True),
    sa.Column('squad_code', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('birth_city', sa.String(), nullable=True),
    sa.Column('scan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passport_il_id'), 'passport_il', ['id'], unique=False)
    op.create_table('accounts_il',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('passport', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passport'], ['passport_il.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('debt_calc_il',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('final_sum', sa.DECIMAL(precision=24, scale=2), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('il_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['il_id'], ['all_il.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_calc_il_id'), 'debt_calc_il', ['id'], unique=False)
    op.create_table('debt_period_il',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('il_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['il_id'], ['all_il.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_period_il_id'), 'debt_period_il', ['id'], unique=False)
    op.create_table('egrn_il',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('il_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['il_id'], ['all_il.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egrn_il_id'), 'egrn_il', ['id'], unique=False)
    op.create_table('judge_orders_exec_il',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('il_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['il_id'], ['all_il.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judge_orders_exec_il_id'), 'judge_orders_exec_il', ['id'], unique=False)
    op.create_table('judge_orders_il',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('il_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['il_id'], ['all_il.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judge_orders_il_id'), 'judge_orders_il', ['id'], unique=False)
    op.create_table('payments_il',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sum', sa.DECIMAL(precision=24, scale=2), nullable=True),
    sa.Column('il_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['il_id'], ['all_il.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_il_id'), 'payments_il', ['id'], unique=False)
    op.create_table('il_accounts',
    sa.Column('il_id', sa.BigInteger(), nullable=False),
    sa.Column('account_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['account_uuid'], ['accounts_il.uuid'], ),
    sa.ForeignKeyConstraint(['il_id'], ['all_il.id'], ),
    sa.PrimaryKeyConstraint('il_id', 'account_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('il_accounts')
    op.drop_index(op.f('ix_payments_il_id'), table_name='payments_il')
    op.drop_table('payments_il')
    op.drop_index(op.f('ix_judge_orders_il_id'), table_name='judge_orders_il')
    op.drop_table('judge_orders_il')
    op.drop_index(op.f('ix_judge_orders_exec_il_id'), table_name='judge_orders_exec_il')
    op.drop_table('judge_orders_exec_il')
    op.drop_index(op.f('ix_egrn_il_id'), table_name='egrn_il')
    op.drop_table('egrn_il')
    op.drop_index(op.f('ix_debt_period_il_id'), table_name='debt_period_il')
    op.drop_table('debt_period_il')
    op.drop_index(op.f('ix_debt_calc_il_id'), table_name='debt_calc_il')
    op.drop_table('debt_calc_il')
    op.drop_table('accounts_il')
    op.drop_index(op.f('ix_passport_il_id'), table_name='passport_il')
    op.drop_table('passport_il')
    op.drop_index(op.f('ix_all_il_id'), table_name='all_il')
    op.drop_table('all_il')
    # ### end Alembic commands ###
